config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'

  resources :policies, only:[:index, :show]
  resources :courses, only:[:index]
  resources :trains, only: [:index]
  resources :jobs, only:[:index]
  resources :raises, only: [:index]
  resources :assists, only:[:index]
  resources :parties, only: [:index]
  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/assists_controller.rb
class AssistsController < ApplicationController
	def index
		
	end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
	def index
		
	end
end

app/controllers/parties_controller.rb
class PartiesController < ApplicationController
	def index
		
	end
end

app/controllers/policies_controller.rb
class PoliciesController < ApplicationController
	def index
		
	end
	
	def show
		
	end
end

app/controllers/raises_controller.rb
class RaisesController < ApplicationController
	def index
		
	end
end

app/controllers/trains_controller.rb
class TrainsController < ApplicationController
	def index
		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assists_helper.rb
module AssistsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/parties_helper.rb
module PartiesHelper
end

app/helpers/policies_helper.rb
module PoliciesHelper
end

app/helpers/raises_helper.rb
module RaisesHelper
end

app/helpers/trains_helper.rb
module TrainsHelper
end

app/views/assists/index.html.erb
<div class="row">
	<div class="col-xs-12">
		<div class="head-blue3">
			<div class="row">
				<div class="head-xs col-xs-4 col-xs-offset-4"></div>
				<div class="head-r col-xs-4"></div>
			</div>
		</div>
		<div class="block clearfix">
			<div class="col-xs-12">
				<p class="block-p pull-left"><span class="glyphicon glyphicon-heart"></span>&nbsp;&nbsp;心理咨询</p>
				<ol class="breadcrumb pull-right">
					<li>所在位置:</li>
					<li><a href="<%= root_path %>">首页</a></li>
					<li class="active">心里辅导</li>
				</ol>
			</div>
			<div class="col-xs-12">
				<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
					<!-- Wrapper for slides -->
					<div class="carousel-inner" role="listbox">
						<div class="item active">
							<div class="col-xs-12">
								<div class="col-xs-2 col-xs-offset-1 text-center">
									<div class="assists-teacher text-center">
										<%=image_tag"counselor.png", width:"100%", height: "200"%>
										<p><strong class="text-primary">张某某</strong><br>国家二级心理咨询师</p>
									</div>
									<p></p>
									<button type="button" class="btn btn-danger btn-sm">在线咨询</button>
								</div>
								<% 4.times do %>
								<div class="col-xs-2 text-center">
									<div class="assists-teacher text-center">
										<%=image_tag"counselor.png", width:"100%", height: "200"%>
										<p><strong class="text-primary">张某某</strong><br>国家二级心理咨询师</p>
									</div>
									<p></p>
									<button type="button" class="btn btn-danger btn-sm">在线咨询</button>
								</div>
								<% end %>	 
							</div>    
						</div>
					</div>

					<!-- Controls -->
					<a class="left carousel-control my-control" href="#carousel-example-generic" role="button" data-slide="prev">
						<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
					</a>
					<a class="right carousel-control my-control" href="#carousel-example-generic" role="button" data-slide="next">
						<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
					</a>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-xs-12"> 
		<div class="block clearfix" style="border-top: 1px solid #ddd;">
			<div class="col-xs-12">
				<ul class="policies-ul">
					<% (1..17).each do |policy| %>
						<li>
							<%= link_to policy_path(policy) do %>
							家庭系统治疗法家庭系统治疗法<span class="pull-right">2015-10-13</span>
							<% end %>
						</li>
					<% end %>
				</ul>
				<nav class="text-center">
					<ul class="pagination">
						<li>
							<a href="#" aria-label="Previous">
								<span aria-hidden="true">&laquo;</span>
							</a>
						</li>
						<li><a href="#">1</a></li>
						<li><a href="#">2</a></li>
						<li><a href="#">3</a></li>
						<li><a href="#">4</a></li>
						<li><a href="#">5</a></li>
						<li>
							<a href="#" aria-label="Next">
								<span aria-hidden="true">&raquo;</span>
							</a>
						</li>
					</ul>
				</nav>
			</div>
		</div>
	</div>
</div>

app/views/courses/index.html.erb
<div class="row">
	<div class="col-md-12">
		<div class="head-blue3">
			<div class="row">
				<div class="head-md col-xs-4 col-xs-offset-4"></div>
				<div class="head-r col-xs-4"></div>
			</div>
		</div>
		<div class="block clearfix">
			<div class="col-md-12">
				<p class="block-p pull-left"><span class="glyphicon glyphicon-list-alt"></span>&nbsp;&nbsp;在线课程</p>
				<ol class="breadcrumb pull-right">
					<li>所在位置:</li>
					<li><a href="<%= root_path %>">首页</a></li>
					<li class="active">在线课程</li>
				</ol>
			</div>
			<div class="col-xs-12 courses-nav">
				<div class="col-xs-2"><a href="#" type="button" class="btn btn-default courses-link active">全部课程</a></div>
				<div class="col-xs-2"><a href="#" type="button" class="btn btn-default courses-link">公务员考试</a></div>
				<div class="col-xs-2"><a href="#" type="button" class="btn btn-default courses-link">职业资格考试</a></div>
				<div class="col-xs-2"><a href="#" type="button" class="btn btn-default courses-link">专业技能考试</a></div>
				<div class="col-xs-2"><a href="#" type="button" class="btn btn-default courses-link">在线培训</a></div>
				<div class="col-xs-2"><a href="#" type="button" class="btn btn-default courses-link">课程展示</a></div>
			</div>
		</div>
		<div class="block clearfix">
			<p></p>
			<div class="col-xs-12">
				<% 9.times do %>
				<div class="col-xs-4">
					<%= image_tag "online_course.png", width: "100%" %>
					<h5 class="text-center">在线课程在线课程在线课程</h5>
				</div>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/home/index.html.erb
<!-- line 1 -->
<div class="row">
	<div class="col-md-4">
		<div class="head-blue2">
			<div class="head-l"><span class="glyphicon"></span>&nbsp;&nbsp;政策指南</div>
			<div class="head-triangle"></div>
			<%= link_to "更多>>", policies_path %>
		</div>
		<div class="block2 clearfix">
			<div class="col-sm-12">
				<ul class="block-ul">
					<li><a href="<%= policy_path(1) %>">国务院关于调整和完善固定资产投资项目...</a></li>
					<li><a href="<%= policy_path(1) %>">国务院办公厅关于推进分级诊疗制度建设...</a></li>
					<li><a href="<%= policy_path(1) %>">国务院办公厅关于批准烟台市城市总体规...</a></li>
					<li><a href="<%= policy_path(1) %>">国务院关于同意设立云南滇中新区的批复...</a></li>
					<li><a href="<%= policy_path(1) %>">国务院办公厅关于加快融资租赁业发展的...</a></li>
				</ul>
			</div>
		</div>
	</div>
	<div class="col-md-4">
		<div class="head-blue2">
			<div class="head-l"><span class="glyphicon glyphicon-list"></span>&nbsp;&nbsp;考证培训信息</div>
			<div class="head-triangle"></div>
			<%= link_to "更多>>", trains_path %>
		</div>
		<div class="block2 clearfix">
			<div class="col-sm-12">
				<ul class="block-ul">
					<li><a href="#">第十期分布式能源培训（北京）</a></li>
					<li><a href="#">事业单位人事管理科学化、养老保险制度改...</a></li>
					<li><a href="#">关于举办政府与社会资本合作与PPP项目方...</a></li>
					<li><a href="#">关于举办事业单位人事管理科学化、养老保...</a></li>
					<li><a href="#">国家发改委培训中心举办行政事业单位财务..</a></li>
				</ul>
			</div>
		</div>
	</div>
	<div class="col-md-4">
		<div class="head-blue2">
			<div class="head-l"><span class="glyphicon glyphicon-user"></span>&nbsp;&nbsp;就业信息</div>
			<div class="head-triangle"></div>
			<%= link_to "更多>>", jobs_path %>
		</div>
		<div class="block2 clearfix">
			<div class="col-md-12">
				<ul class="block-ul">
					<li><a href="#">第十期分布式能源培训（北京）</a></li>
					<li><a href="#">事业单位人事管理科学化、养老保险制度改...</a></li>
					<li><a href="#">关于举办政府与社会资本合作与PPP项目方...</a></li>
					<li><a href="#">关于举办事业单位人事管理科学化、养老保...</a></li>
					<li><a href="#">国家发改委培训中心举办行政事业单位财务...</a></li>
				</ul>
			</div>
		</div>
	</div>
</div>
<!-- line 2 -->
<div class="row">
	<div class="col-md-12">
		<div class="head-blue3">
			<div class="row">
				<div class="head-md col-xs-4 col-xs-offset-4"></div>
				<div class="head-r col-xs-4"><%= link_to "更多>>", raises_path %></div>
			</div>
		</div>
		<div class="block clearfix">
			<div class="col-md-12">
				<p class="block-p"><span class="glyphicon glyphicon-usd"></span>&nbsp;&nbsp;创业众筹</p>
				<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
					<!-- Wrapper for slides -->
					<div class="carousel-inner" role="listbox">
						<div class="item active">
							<div class="col-md-12">
								<div class="col-md-3 text-center">
									<%=image_tag"invest_project1.png", width:"100%", height: "145"%>
									<p>项目投资项目投资</p>
								</div>
								<div class="col-md-3 text-center">
									<%=image_tag"invest_project2.png", width:"100%", height: "145"%>
									<p>项目投资项目投资</p>
								</div>
								<div class="col-md-3 text-center">
									<%=image_tag"invest_project3.png", width:"100%", height: "145"%>
									<p>项目投资项目投资</p>
								</div>
								<div class="col-md-3 text-center">
									<%=image_tag"invest_project4.png", width:"100%", height: "145"%>
									<p>项目投资项目投资</p>
								</div>		 
							</div>    
						</div>
						<div class="item">
							<div class="col-md-12">
								<div class="col-md-3 text-center">
									<%=image_tag"invest_project1.png", width:"100%", height: "145"%>
									<p>项目投资项目投资</p>
								</div>
								<div class="col-md-3 text-center">
									<%=image_tag"invest_project2.png", width:"100%", height: "145"%>
									<p>项目投资项目投资</p>
								</div>
								<div class="col-md-3 text-center">
									<%=image_tag"invest_project3.png", width:"100%", height: "145"%>
									<p>项目投资项目投资</p>
								</div>
								<div class="col-md-3 text-center">
									<%=image_tag"invest_project4.png", width:"100%", height: "145"%>
									<p>项目投资项目投资</p>
								</div>		 
							</div>		     
						</div>
					</div>

					<!-- Controls -->
					<a class="left carousel-control my-control" href="#carousel-example-generic" role="button" data-slide="prev">
						<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
					</a>
					<a class="right carousel-control my-control" href="#carousel-example-generic" role="button" data-slide="next">
						<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
					</a>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- line 3 -->
<div class="row" style="overflow: hidden;">
	<div class="col-md-4">
		<div class="head-blue">
			<span>icon</span> 在线课程<%= link_to "更多>>", courses_path %>
		</div>
		<div class="block clearfix">
			<% 2.times do %>
				<div class="row">
					<div class="col-xs-5"><%= image_tag("online_course.png", class: "img-responsive") %></div>
					<div class="col-xs-7">
						<h5>军转干课程军转干课程</h5>
						<p class="text-muted">军转干课程军转干课程军转干课程军转干课程军转干课程</p>
					</div>
				</div>
				<hr class="courses-hr">
			<% end %>
			<div class="row">
				<div class="col-xs-5"><%= image_tag("online_course.png", class: "img-responsive") %></div>
				<div class="col-xs-7">
					<h5>军转干课程军转干课程</h5>
					<p class="text-muted">军转干课程军转干课程军转干课程军转干课程军转干课程</p>
				</div>
			</div>
		</div>
	</div>
	<div class="col-md-4">
		<div class="head-blue">
			<span class="glyphicon glyphicon-heart"></span> 心里咨询<%= link_to "更多>>", assists_path %>
		</div>
		<div class="block clearfix">
			<div class="col-md-12">
				<ul class="block-ul">
					<li><a href="#">心理咨询的文章心理咨询的文章心理咨询的...</a></li>
					<li><a href="#">心理咨询的文章心理咨询的文章心理咨询的...</a></li>
					<li><a href="#">心理咨询的文章心理咨询的文章心理咨询的...</a></li>
					<li><a href="#">心理咨询的文章心理咨询的文章心理咨询的...</a></li>
					<li><a href="#">心理咨询的文章心理咨询的文章心理咨询的...</a></li>
					<li><a href="#">心理咨询的文章心理咨询的文章心理咨询的...</a></li>
				</ul>
			</div>
		</div>
	</div>
	<div class="col-md-4">
		<div class="head-blue">
			<span>icon</span> 军友会<%= link_to "更多>>", parties_path %>
		</div>
		<div class="block clearfix">
			<div class="col-md-12">
				<ul class="block-ul">
					<li><a href="#">军转干信息登记<span class="text-danger">（急急急）</span></a></li>
					<li><a href="#">军转干信息登记军转干信息登记</a></li>
					<li><a href="#">军转干信息登记<span class="text-danger">（急急急）</span></a></li>
					<li><a href="#">军转干信息登记军转干信息登记<span class="text-danger">（急急急）</span></a></li>
					<li><a href="#">军转干信息登记军转干信息登记</a></li>
					<li><a href="#">军转干信息登记军转干信息登记</a></li>
				</ul>
			</div>
		</div>
	</div>
</div>

app/views/jobs/index.html.erb
<div class="row">
	<div class="col-md-12">
		<div class="head-blue3">
			<div class="row">
				<div class="head-md col-xs-4 col-xs-offset-4"></div>
				<div class="head-r col-xs-4"></div>
			</div>
		</div>
		<div class="block clearfix">
			<div class="col-md-12">
				<p class="block-p pull-left"><span class="glyphicon glyphicon-list-alt"></span>&nbsp;&nbsp;在线课程</p>
				<ol class="breadcrumb pull-right">
					<li>所在位置:</li>
					<li><a href="<%= root_path %>">首页</a></li>
					<li class="active">在线课程</li>
				</ol>
			</div>
			<div class="col-xs-12 courses-nav">
				<form class="form-inline">
					<div class="form-group col-xs-2">
						<div class="dropdown">
							<button class="btn btn-default btn-job dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
								地点
								<span class="caret"></span>
							</button>
							<ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
								<li><a href="#">上海</a></li>
								<li><a href="#">北京</a></li>
							</ul>
						</div>
					</div>
					<div class="form-group col-xs-2">
						<div class="dropdown">
							<button class="btn btn-default btn-job dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
								职位
								<span class="caret"></span>
							</button>
							<ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
								<li><a href="#">老师</a></li>
								<li><a href="#">工程师</a></li>
							</ul>
						</div>
					</div>
					<div class="form-group col-xs-6">
						<input type="text" class="form-control" style="width: 100%;" placeholder="关键字搜索">
					</div>
					<div class="col-xs-1"><button type="submit" class="btn btn-success btn-job">搜索</button></div>
				</form>
			</div>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-md-12"> 
		<div class="gray-head" style="padding: 0 60px;">
			<div class="row">
				<div class="col-xs-6" style="text-indent: 60px;">公司名称</div>
				<div class="col-xs-3" style="text-indent: 30px;">职位名称</div>
				<div class="col-xs-3 text-center">发布时间</div>
			</div>
		</div>
		<div class="block clearfix">
			<div class="col-xs-12">
				<ul class="policies-ul" style="list-style-type: none;">
					<% (1..17).each do |policy| %>
						<li>
							<%= link_to "#" do %>
								<div class="row">
									<div class="col-xs-6">[北京] 北京市安伦律师事务所</div>
									<div class="col-xs-3">律所实习生招聘</div>
									<div class="col-xs-3 text-center">2015-10-13</div>
								</div>
							<% end %>
						</li>
					<% end %>
				</ul>
				<nav class="text-center">
					<ul class="pagination">
						<li>
							<a href="#" aria-label="Previous">
								<span aria-hidden="true">&laquo;</span>
							</a>
						</li>
						<li><a href="#">1</a></li>
						<li><a href="#">2</a></li>
						<li><a href="#">3</a></li>
						<li><a href="#">4</a></li>
						<li><a href="#">5</a></li>
						<li>
							<a href="#" aria-label="Next">
								<span aria-hidden="true">&raquo;</span>
							</a>
						</li>
					</ul>
				</nav>
			</div>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pawn</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<!-- <p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p> -->
  <% if params[:controller].include?("devise") %>
    <%= yield %>
  <% else %>
    <div class="container">
      <%= render partial: "share/topbar" %>
    	<%= yield %>
      <%= render partial: "share/footer" %>
    </div>
  <% end %>
</body>
</html>

app/views/parties/index.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="head-blue3">
      <div class="row">
        <div class="head-md col-xs-4 col-xs-offset-4"></div>
      </div>
    </div>
    <div class="block clearfix">
      <div class="col-md-12">
        <p class="block-p pull-left"><span class="glyphicon glyphicon-usd"></span>&nbsp;&nbsp;军友会</p>
        <ol class="breadcrumb pull-right">
          <li>所在位置:</li>
          <li><a href="<%= root_path %>">首页</a></li>
          <li class="active">军友会</li>
        </ol>
      </div>
      <div class="col-xs-12 courses-nav">
        <div class="col-xs-2"><a href="#" type="button" class="btn btn-default courses-link active">全部帖子</a></div>
        <div class="col-xs-2"><a href="#" type="button" class="btn btn-default courses-link">互帮互助</a></div>
        <div class="col-xs-2"><a href="#" type="button" class="btn btn-default courses-link">资源共享</a></div>
        <div class="col-xs-2"><a href="#" type="button" class="btn btn-default courses-link">关于军转干</a></div>
        <div class="col-xs-2"><a href="#" type="button" class="btn btn-default courses-link">考证培训</a></div>
        <div class="col-xs-2"><a href="#" type="button" class="btn btn-default courses-link">其他</a></div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12"> 
        <!-- <div class="gray-head" style="padding: 0 60px;">
          <div class="row">
            <div class="col-xs-6" style="text-indent: 60px;">公司名称</div>
            <div class="col-xs-3" style="text-indent: 30px;">职位名称</div>
            <div class="col-xs-3 text-center">发布时间</div>
          </div>
        </div> -->
        <%= image_tag "soldier1.png", width: "100%" %>
      </div>
    </div>
    <div class="row parties-soldier2">
      <div class="col-md-12">
        <%= image_tag "soldier2.png", width: "100%" %>
      </div>
    </div>
  </div>
</div>

app/views/policies/index.html.erb
<div class="row">
	<div class="col-md-12"> 
		<div class="head-blue3">
			<div class="row">
				<div class="head-md col-xs-4 col-xs-offset-4"></div>
				<div class="head-r col-xs-4"></div>
			</div>
		</div>
		<div class="block clearfix">
			<div class="col-xs-12">
				<div class="col-xs-6 policies-title">
					<span class="glyphicon glyphicon-time"></span>&nbsp;&nbsp;政策指南
				</div>
				<div class="col-xs-6">
					<ol class="breadcrumb pull-right">
						<li>所在位置:</li>
						<li><a href="<%= root_path %>">首页</a></li>
						<li class="active">政策指南</li>
					</ol>
				</div>
			</div>
			<div class="col-xs-12">
				<ul class="policies-ul">
					<% (1..17).each do |policy| %>
						<li>
							<%= link_to policy_path(policy) do %>
							国务院关于苏州工业园区开展开放创新综合实验总体方案的批复<span class="pull-right">2015-10-13</span>
							<% end %>
						</li>
					<% end %>
				</ul>
				<nav class="text-center">
					<ul class="pagination">
						<li>
							<a href="#" aria-label="Previous">
								<span aria-hidden="true">&laquo;</span>
							</a>
						</li>
						<li><a href="#">1</a></li>
						<li><a href="#">2</a></li>
						<li><a href="#">3</a></li>
						<li><a href="#">4</a></li>
						<li><a href="#">5</a></li>
						<li>
							<a href="#" aria-label="Next">
								<span aria-hidden="true">&raquo;</span>
							</a>
						</li>
					</ul>
				</nav>
			</div>
		</div>
	</div>
</div>

app/views/policies/show.html.erb
<div class="row">
	<div class="col-md-12">
		<div class="head-blue2">
			<div class="head-l"><span class="glyphicon glyphicon-time"></span>&nbsp;&nbsp;政策指南</div>
			<div class="head-triangle"></div>
			<ol class="breadcrumb show-crumb pull-right">
				<li>所在位置:</li>
				<li><a href="<%= root_path %>">首页</a></li>
				<li><%= link_to "政策指南", policies_path %></li>
				<li class="active">正文</li>
			</ol>
		</div>
		<div class="block2 clearfix">
			<div class="col-xs-12">
				<h4 class="text-center" style="color: #2E6699;">国务院关于调整和完善固定资产投资项目资本金制度的通知</h4>
				<hr class="policy-hr">
				<%= image_tag("policy_content.png", width: "100%") %>
			</div>
		</div>
	</div>
</div>

app/views/share/_footer.html.erb
<div class="footer">
	<div class="footer-info text-center">
		<span>这里是底部信息这里是底部信息这里是底部信息这里是底部信息这里是底部信息</span>
	</div>
</div>

app/views/share/_topbar.html.erb
<%= image_tag"banner.png", width:"100%" %>

<nav class="navbar navbar-default my-navbar">
	<div class="container-fluid">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
		</div>

		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav">
				<li class="navbar-first <%= "active" if params[:controller] == "home" %>"><%= link_to "首页", root_path %></li>
				<li class="<%= "active" if params[:controller] == "policies" %>"><%= link_to "政策指南", policies_path %></li>
				<li class="<%= "active" if params[:controller] == "courses" %>"><%= link_to "在线课程", courses_path %></li>
				<li class="<%= "active" if params[:controller] == "trains" %>"><%= link_to "考证培训", trains_path %></li>
				<li class="<%= "active" if params[:controller] == "jobs" %>"><%= link_to "就业信息", jobs_path %></li>
				<li class="<%= "active" if params[:controller] == "raises" %>"><%= link_to "创业众筹", raises_path %></li>
				<li class="<%= "active" if params[:controller] == "assists" %>"><%= link_to "心理辅导", assists_path %></li>
				<li class="navbar-last <%= "active" if params[:controller] == "parties" %>"><%= link_to "军友会", parties_path %></li>
			</ul>
			<ul class="nav navbar-nav navbar-right">
				<% if current_user %>
					<li><%= link_to('修改密码', edit_registration_path(:user)) %></li>
			  		<li><%= link_to('退出', destroy_user_session_path, :method => :delete) %></li>
			  	<% else %>
			  		<li><%= link_to('登录', new_session_path(:user)) %></li>
			  		<li><%= link_to('注册', new_registration_path(:user)) %></li>
			  	<% end %>
			</ul>
		</div><!-- /.navbar-collapse -->
	</div><!-- /.container-fluid -->
</nav>